---

- name: Install nginx
  ansible.builtin.apt:
    name:
      - nginx
      - python3-certbot
    state: present
  become: true

- name: Set up default config
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/nginx/sites-enabled/default
  become: true
  notify: restart nginx

- name: Add default index page
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true

- name: Create directory for certbot renewals
  ansible.builtin.file:
    path: /var/www/letsencrypt
    state: directory
  become: true

- name: Setup cronjob for renewal
  ansible.builtin.cron:
    name: certbot-renewal
    job: /usr/local/bin/certbot -q renew && nginx -t && nginx -t reload
    minute: "10"
    hour: "18"
  become: true
