---
- name: Install cifs-utils
  ansible.builtin.apt:
    name: cifs-utils
    state: present
  become: yes

- name: Mount NAS
  ansible.posix.mount:
    path: /mnt/nas
    src: //nas.home.chandlerswift.com/chandlerpublic
    fstype: cifs
    state: mounted
    opts: "guest"
  become: yes
