---
# Additional setup:
# * Install Debian 11
#   - `chandler` as sudo-enabled user
#   - ssh server enabled
# * Set up static IP in router: https://pfsense.home.chandlerswift.com/services_dhcp_edit.php?if=lan&id=1
- name: Setup Zirconium
  hosts: zirconium.home.chandlerswift.com
  roles:
  - common
  - mount-nas
  - role: navidrome
    vars:
      navidrome_version: 0.49.3
  - peertube
  - role: forwarder
    vars:
      server_names:
        - preview.chandlerswift.com
      proxy_pass: http://xenon.home.chandlerswift.com:4000/
      additional_https_config: |
        location /livereload {
            include proxy_params;
            proxy_pass http://xenon.home.chandlerswift.com:4000/livereload;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
  - role: forwarder
    vars:
      server_names:
        - isaacswift.com
        - www.isaacswift.com
      proxy_pass: http://isaac.home.chandlerswift.com/
  - role: static-fileserver
    vars:
      server_names:
        - 0hats.com
        - www.0hats.com
  - role: static-fileserver
    vars:
      server_names:
        - home.chandlerswift.com
  - darylfanclub
  - flintlock
  - role: forwarder
    vars:
      server_names:
        - whereis.chandlerswift.com
      proxy_pass: http://localhost:8083/
  # owntracks-recorder must be after the whereis.chandlerswift.com forwarder,
  # since it uses the TLS keypair from that domain.
  - owntracks-recorder # TODO: save data off of zirconium
  - role: forwarder
    vars:
      server_names:
        - maps.chandlerswift.com
      proxy_pass: http://maps.home.chandlerswift.com:8080/
  - immich
  - role: forwarder
    vars:
      server_names:
        - photos.chandlerswift.com
      proxy_pass: http://localhost:2283/
      additional_https_config: |
        client_max_body_size 12G; # default is 1M
