---
- name: Create navidrome user
  ansible.builtin.user:
    name: navidrome
    shell: /usr/bin/false
  become: yes

# https://www.navidrome.org/docs/installation/linux/

- name: Install ffmpeg
  ansible.builtin.apt:
    name: ffmpeg
    state: present
  become: yes

- name: Extract navidrome
  ansible.builtin.unarchive:
    src: https://github.com/navidrome/navidrome/releases/download/v{{ navidrome_version }}/navidrome_{{ navidrome_version }}_linux_amd64.tar.gz
    dest: /home/navidrome
    remote_src: yes
    owner: navidrome
  notify: restart navidrome
  become: yes

- name: Add navidrome config
  ansible.builtin.copy:
    src: navidrome.toml
    dest: /home/navidrome/navidrome.toml
    owner: navidrome
  notify: restart navidrome
  become: yes

- name: Install navidrome service
  ansible.builtin.copy:
    src: navidrome.service
    dest: /lib/systemd/system/navidrome.service
  become: yes
  register: service

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
  when: service.changed

- name: Start/enable navidrome
  ansible.builtin.systemd:
    name: navidrome
    enabled: yes
    state: started
  become: yes

- ansible.builtin.include_role:
    name: forwarder
  vars:
    server_names:
      - music.chandlerswift.com
    proxy_pass: http://localhost:4533/
