---
- ansible.builtin.file:
    path: /var/www/com/0hats
    state: directory
  become: true

# TODO: generate and copy the actual file!

- name: Get certificate
  ansible.builtin.command:
    cmd: certbot --agree-tos --email chandler@chandlerswift.com -n certonly -d 0hats.com,www.0hats.com --webroot --webroot-path /var/www/letsencrypt --post-hook "systemctl restart nginx"
    creates: /etc/letsencrypt/live/0hats.com
  become: true
  notify: restart nginx

- name: Configure nginx
  ansible.builtin.copy:
    src: com.0hats.conf
    dest: /etc/nginx/sites-enabled/com.0hats.conf
  become: true
  notify: restart nginx
