---
- name: Add `chandler` account
  ansible.builtin.user:
    name: chandler
    comment: Chandler Swift
    groups: sudo
  become: true

- name: Set up SSH
  ansible.builtin.import_tasks: ssh.yml

- name: Set passwordless sudo (Debian)
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo ALL='
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
  become: true
  when: ansible_facts.distribution != "Archlinux"

- name: Set passwordless sudo (Arch)
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel ALL='
    line: '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
  become: true
  when: ansible_facts.distribution == "Archlinux"

- name: Install rsync
  ansible.builtin.package:
    name: rsync
    state: present
  become: true
