---
- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
  become: yes

- name: Add user to Docker group
  ansible.builtin.user:
    name: chandler
    groups: docker
    append: yes
  become: yes
